#!/bin/bash
set -e

if [ $# -gt 0 ]; then
  exec "$@"
fi

# If using postgres db, make sure pg_trgm extension is enabled.
DB_DRIVER=$(drush eval "return \Drupal\Core\Database\Database::getConnectionInfo()['default']['driver']")
if [ $DB_DRIVER == "pgsql" ]; then
  # Wait for postgres to start accepting connections.
  # When running postgres in docker container it usually starts accepting
  # connections after small delay compared to when container is reported as
  # running.
  RETRIES=5
  until drush sql:query "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
    echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
    sleep 1
  done
  # Enable pg_trgm extension.
  drush sql:query "create extension if not exists pg_trgm;"
fi

# Start php-fpm.
/usr/sbin/php-fpm8.1 -D

# Start apache.
exec apache2ctl -D FOREGROUND
