version: '3.9'

services:

  farmos:
    image: ghcr.io/wotnak/farmos:main
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/files:/opt/farmos/web/sites/default/files
      - ./data/private_files:/opt/farmos/private_files
    depends_on:
      - db
    ports:
      - 80:80

  db:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $FARMOS_DB_USER
      POSTGRES_PASSWORD: $FARMOS_DB_PASS
      POSTGRES_DB: $FARMOS_DB_NAME
